services:
  backend:
    profiles:
      - full
    build:
      context: ..
      dockerfile: packages/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      SQLITE_PATH: /app/data/dsa.db
    volumes:
      - ../data/sqlite:/app/data
